"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭╴](fg:#505050)\
$os\
$shell\
$username\
$hostname\
$sudo\
$directory\
$direnv\
$php\
$python\
$git_branch$git_commit$git_state$git_metrics$git_status\
[ ](fg:#252525)\
$fill\
$fill\
[ ](fg:#252525)\
$status\
$jobs\
$memory_usage\
$cmd_duration\
$battery\
$time\
$line_break\
\
[╰╴](fg:#505050)\
[$character]($style)"""

right_format = """
[$localip]($style)"""

add_newline = true

[os]
format = "[](fg:#252525)[$symbol]($style)(bg:#252525)"
style = "fg:#AAAAAA bg:#252525"
disabled = false

[os.symbols]
AIX = "AIX "
Alpaquita = "\uf26a "
AlmaLinux = "\uf31d "
Alpine = "\uf300 "
Amazon = "\uf270 "
Android = "\ue70e "
Arch = "\uf303 "
Artix = "\uf31f "
CentOS = "\uf304 "
Debian = "\uf306 "
DragonFly = "\ueef8 "
Emscripten = "\u26A1 "
EndeavourOS = "\uf322 "
Fedora = "\uf30a "
FreeBSD = "\uf30c "
Garuda = "\uf337 "
Gentoo = "\uf30d "
HardenedBSD = "\uf132 "
Illumos = "\uf326 "
Kali = "\uf327 "
Linux = "\uf17c "
Mabox = "\uf1b2 "
Macos = "\uf302 "
Manjaro = "\uf312 "
Mariner = "\ue7ae "
MidnightBSD = "\ue3e0 "
Mint = "\uf30e "
NetBSD = "\u2691 "
NixOS = "\uf313 "
OpenBSD = "\uf328 "
OpenCloudOS = "\uf0c2 "
openEuler = "\u2208 "
openSUSE = "\uf314 "
OracleLinux = "\u213A "
Pop = "\uf32a "
Raspbian = "\uf315 "
Redhat = "\uf316 "
RedHatEnterprise = "\uf316 "
RockyLinux = "\uf32b "
Redox = "\uf331 "
Solus = "\uf32d "
SUSE = "\uef6d "
Ubuntu = "\uf31b "
Ultramarine = "󱙳 "
Unknown = "\uf108 "
Void = "\uf32e "
Windows = "\uf17a "

[shell]
format = '[$indicator]($style)()'
style = 'fg:#424242 bg:#252525'
zsh_indicator = '%_ '
bash_indicator = '\$_ '
fish_indicator = '>> '
powershell_indicator = '>_ '
unknown_indicator = '?_ '
disabled = true

[username]
format = '[ ](fg:green bold bg:#252525)[$user]($style)[ ](bg:#252525)'
style_user = 'fg:green bold bg:#252525'
style_root = 'fg:red bold bg:#252525'
show_always = false
disabled = false

[hostname]
format = '[$ssh_symbol ](fg:green bold bg:#252525)[$hostname](fg:green bold bg:#252525)[ ](bg:#252525)'
ssh_only = true
ssh_symbol = ''
disabled = false

[sudo]
format = '[ ](fg:red bold bg:#252525)[ $symbol]($style)'
style = 'fg:red bold bg:#252525'
symbol = ' '
disabled = false

[directory]
format = '[ ](fg:cyan bold bg:#252525)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path ]($style)'
style = 'fg:cyan bold bg:#252525'
home_symbol = ' ~'
read_only = ' '
read_only_style = 'fg:cyan bg:#252525'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true
repo_root_format = '[ ](fg:cyan bold bg:#252525)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)'
repo_root_style = 'fg:cyan bold bg:#252525'
use_os_path_sep = true
disabled = false

[direnv]
symbol = 'direnv'
style = 'fg:#505050 bold bg:#252525'
format = "[❯ $symbol $loaded/$allowed ]($style)"
allowed_msg = 'a'
not_allowed_msg = '!a'
denied_msg = 'x'
loaded_msg = '+'
unloaded_msg = '-'
disabled = false

[php]
format = "[[ \u3009](fg:#7a86b8 bg:#252525)[$symbol](fg:#7a86b8 italic bg:#252525)($version )]($style)"
style = 'fg:#7a86b8 bg:#252525)'
symbol = "php "

[python]
format = "[\u3009${symbol}${pyenv_prefix}(${version} )(($virtualenv) )]($style)"
style = 'fg:yellow bg:#252525'
symbol = "󰌠 "
pyenv_version_name = true

[git_branch]
format = '[❯ $symbol $branch(:$remote_branch)]($style)[ ](bg:#252525)'
style = 'fg:#E04D27 bg:#252525'
symbol = ''

[git_commit]
format = '[\($hash$tag\)]($style)[ ](bg:#252525)'
style = 'fg:#2d838c bg:#252525'
commit_hash_length = 8
tag_symbol = '  '
tag_disabled = false
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ](bg:#252525)'
added_style = 'fg:#3b8f28 bg:#252525'
deleted_style = 'fg:#94482f bg:#252525'
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'fg:#E04D27 bg:#252525'
conflicted = '[ ${count} ](fg:red bg:#252525)'
ahead = '[ ${count} ](fg:yellow bg:#252525)'
behind = '[ ${count} ](fg:yellow bg:#252525)'
diverged = '[ ${ahead_count} ${behind_count} ](fg:yellow bg:#252525)'
up_to_date = '[ ](fg:green bg:#252525)'
untracked = '[ ${count} ](fg:red bg:#252525)'
stashed = '[ ${count} ](fg:#A52A2A bg:#252525)'
modified = '[ ${count} ](fg:#C8AC00 bg:#252525)'
staged = '[ ${count} ](fg:green bg:#252525)'
renamed = '[ ${count} ](fg:yellow bg:#252525)'
deleted = '[ ${count} ](fg:red bg:#252525)'
disabled = false

[fill]
symbol = " "
disabled = false

[status]
format = '[❯$symbol]($style)'
style = 'fg:#252525 bg:#2f3447'
symbol = '❯'
disabled = false

[jobs]
format = '[ ](fg:#AA8B1D bg:#252525)[$number]($style)'
style = 'fg:#AA8B1D bg:#252525'
disabled = false

[memory_usage]
format = '[ ](fg:#EA8054 bg:#252525)[$symbol$ram]($style)'
style = 'fg:#EA8054 bg:#252525'
symbol = '󰍛 '
disabled = false

[cmd_duration]
format = '[ ](fg:#6D59E3 bg:#252525)[$duration]($style)'
style = 'fg:#6D59E3 bg:#252525'
min_time = 5_000
disabled = false

[battery]
format = '[ ](fg:#E0B20F bg:#252525)[$symbol$percentage]($style)'
style = 'fg:#E0B20F bg:#252525'
symbol = ' '
disabled = true

[time]
disabled = false
format = '[ ](fg:#8AB4F8 bg:#252525)[ $time]($style)'
style = 'fg:#8AB4F8 bg:#252525'
time_format = "%H:%M:%S"

[localip]
format = '[󰩟 $ip]($style)'
style = 'fg:#505050 bg:#252525'
disabled = false
