# Start window index từ 1
set-option -g base-index 1
setw -g pane-base-index 1

# Terminal colors & TrueColor support
set-option -g default-terminal "tmux-256color"
set-option -as terminal-features ",xterm-256color:RGB"

# Enable undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# Enable undercurl colors
set -as terminal-overrides ',*:Setbc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Trải nghiệm người dùng
set -s escape-time 0
set -g allow-passthrough on
set-option -g focus-events on
set-option -g set-clipboard on
set-option -g history-limit 100000
set-option -g mouse on
set-option -g set-titles on
set-option -g set-titles-string "#S: #W"

# Vi mode
setw -g mode-keys vi
set-option -g status-keys vi

# Prevent automatic renaming (keep manual names)
set-option -g allow-rename off
set-window-option -g automatic-rename off

# Fix auto-scrolling
bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down

# run-shell '~/.tmux/plugins/tmux-resurrect/scripts/restore.sh' (Đã có continuum-restore)

