set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Resurrect settings
set -g @resurrect-save 'on'
set -g @resurrect-strategy-nvim 'session'

# Keybindings cho Resurrect (sử dụng Prefix Ctrl-a)
bind-key C-s run-shell '~/.tmux/plugins/tpm/bin/install_plugins; ~/.tmux/plugins/tmux-resurrect/scripts/save.sh'
bind-key C-r run-shell '~/.tmux/plugins/tmux-resurrect/scripts/restore.sh'
