# Color palette
RED="#ea6962"
GREEN="#36A12F"
YELLOW="#d8a657"
BLUE="#7daea3"
MAGENTA="#d3869b"
CYAN="#89cff0"
WHITE="#FFFFFF"
DARK_GRAY="#32302F"
LIGHT_GRAY="#4F4946"
BG="#32302F"
FG="#d4be98"

# Nerdfont icons
HALF_ROUND_OPEN=""
HALF_ROUND_CLOSE=""
TRIANGLE_OPEN=""
TRIANGLE_CLOSE=""

# Status bar position & style
set-option -g status-style bg=${BG},fg=${FG}
set-option -g status-justify centre
set-option -g status-left-length 100
set-option -g status-right-length 100

# Status left: user + shell + session
set-option -g status-left "\
#[fg=${CYAN},bg=default]${TRIANGLE_OPEN}\
#[bg=${CYAN},fg=${WHITE}]   #(whoami)@#h \
#[fg=${CYAN},bg=default]${HALF_ROUND_CLOSE}\
#[fg=${GREEN},bg=default]${TRIANGLE_OPEN}\
#[bg=${GREEN},fg=${WHITE}]   #(basename $SHELL) \
#[fg=${GREEN},bg=default]${HALF_ROUND_CLOSE}\
#[fg=${YELLOW},bg=default]${TRIANGLE_OPEN}\
#[bg=${YELLOW},fg=${WHITE}] #S \
#[fg=${YELLOW},bg=default]${HALF_ROUND_CLOSE}\
"

# Status right: time + date + hostname
set-option -g status-right "\
#[fg=${YELLOW},bg=default]${TRIANGLE_OPEN}\
#[bg=${YELLOW},fg=${WHITE}] %A \
#[fg=${YELLOW},bg=default]${HALF_ROUND_CLOSE}\
#[fg=${GREEN},bg=default]${TRIANGLE_OPEN}\
#[bg=${GREEN},fg=${WHITE}]  %d-%m-%Y \
#[fg=${GREEN},bg=default]${HALF_ROUND_CLOSE}\
#[fg=${CYAN},bg=default]${TRIANGLE_OPEN}\
#[bg=${CYAN},fg=${WHITE}]  #h \
#[fg=${CYAN},bg=default]${HALF_ROUND_CLOSE}\
"

# Window list style
set-option -g window-status-format " #I#[fg=${MAGENTA}]:#[fg=default]#W "
set-option -g window-status-current-format "\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_OPEN}\
#[bg=${LIGHT_GRAY},fg=default]#I#[fg=${RED}]:#[fg=default]#W\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_CLOSE}\
"
