# Catppuccin Mocha Palette
rosewater="#f5e0dc"
flamingo="#f2cdcd"
pink="#f5c2e7"
mauve="#cba6f7"
red="#f38ba8"
maroon="#eba0ac"
peach="#fab387"
yellow="#f9e2af"
green="#a6e3a1"
teal="#94e2d5"
sky="#89dceb"
sapphire="#74c7ec"
blue="#89b4fa"
lavender="#b4befe"
text="#cdd6f4"
subtext1="#bac2de"
subtext0="#a6adc8"
overlay2="#9399b2"
overlay1="#7f849c"
overlay0="#6c7086"
surface2="#585b70"
surface1="#45475a"
surface0="#313244"
base="#1e1e2e"
mantle="#181825"
crust="#11111b"

# Status bar options
set-option -g status-position bottom
set-option -g status-style bg=default,fg=${text}
set-option -g status-justify centre
set-option -g status-left-length 100
set-option -g status-right-length 100

# Pane borders
set-option -g pane-border-style fg=${surface1}
set-option -g pane-active-border-style fg=${mauve}

# Message style
set-option -g message-style bg=${surface0},fg=${mauve},bold

# Status Left: Session + User
set-option -g status-left "\
#[fg=${blue},bg=default]\
#[fg=${crust},bg=${blue},bold]  #S \
#[fg=${blue},bg=${surface0}]\
#[fg=${text},bg=${surface0}]  #(whoami) \
#[fg=${surface0},bg=default]\
"

# Status Right: Time + Date
set-option -g status-right "\
#[fg=${surface0},bg=default]\
#[fg=${text},bg=${surface0}]  %d-%m-%Y \
#[fg=${mauve},bg=${surface0}]\
#[fg=${crust},bg=${mauve},bold] 󱑒 %H:%M \
#[fg=${mauve},bg=default]\
"

# Window List Style
set-window-option -g window-status-separator " "
set-window-option -g window-status-format "\
#[fg=${surface1},bg=default]\
#[fg=${text},bg=${surface1}] #I #W \
#[fg=${surface1},bg=default]\
"
set-window-option -g window-status-current-format "\
#[fg=${mauve},bg=default]\
#[fg=${crust},bg=${mauve},bold] #I #W \
#[fg=${mauve},bg=default]\
"
