gesture swipe left   3 xdotool key Alt+Tab
gesture swipe right  3 xdotool key Alt+Tab
gesture swipe up     3 xdotool key Super_L
gesture swipe down   3 xdotool key Super_L 

gesture swipe left   4 xdotool key Ctrl+Alt+Right
gesture swipe right  4 xdotool key Ctrl+Alt+Left
gesture swipe down   4 xdotool key Ctrl+Alt+t
gesture swipe up     4  google-chrome

gesture pinch in    2 xdotool key Ctrl+minus
gesture pinch out   2 xdotool key Ctrl+equal
