# Nạp các file cấu hình nhỏ
source-file ~/.tmux/options.conf
source-file ~/.tmux/keybindings.conf
source-file ~/.tmux/theme.conf
source-file ~/.tmux/plugins.conf

# Load TPM (Luôn để ở cuối cùng)
run '~/.tmux/plugins/tpm/tpm'


